# Generated by Django 3.0 on 2022-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intership_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='uom',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
